### ISSUE TITLE
INSTALL.pl assumes sudo is installed but fails to install anything

### ISSUE THREAD

**Issue by eburgueno** [Ensembl/Bio-DB-HTS#81]
The `INSTALL.pl` script assumes `sudo` is installed in the system, and warns "If this step fails... run this script again as superuser". If `sudo` is not installed, the script does not install anything, and prints the success message. Running the script as `root` does not actually do anything.

From a Docker container running `ubuntu:bionic` (ie: `docker run -ti --rm ubuntu:bionic bash`):
```
# apt-get update && apt-get -y install bioperl gcc git libbz2-dev liblzma-dev libmodule-build-perl make wget zlib1g-dev
# id
uid=0(root) gid=0(root) groups=0(root)
# cat /etc/issue
Ubuntu 18.04.1 LTS \n \l
# cd /opt ; wget https://github.com/Ensembl/Bio-DB-HTS/archive/2.11.tar.gz ; tar -xzf 2.11.tar.gz ; cd Bio-DB-HTS-2.11; ./INSTALL.pl 
/opt/Bio-DB-HTS-2.11

*** Performing build in /tmp/FyEvcsvHL7 ***
(...)
*** Installing Bio::DB::HTS using sudo. You will be asked for your password. ***

*** If this step fails because sudo isn't installed, go back and run this script again as superuser. ***

*** Bio::DB::HTS v2.11 is now installed. ***

# ls /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/
ls: cannot access '/usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS/': No such file or directory
```

Behaviour when `sudo` is installed. Note that I am still `root`, so using `sudo` here is redundant.
```
# apt-get -y install sudo
# ./INSTALL.pl
/opt/Bio-DB-HTS-2.11

*** Performing build in /tmp/AoqhX1iJBN ***
(...)
*** Installing Bio::DB::HTS using sudo. You will be asked for your password. ***

*** If this step fails because sudo isn't installed, go back and run this script again as superuser. ***
Building Bio-DB-HTS
Files found in blib/arch: installing files in blib/lib into architecture dependent library tree
Installing /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/auto/Bio/DB/HTS/HTS.so
(...)
*** Bio::DB::HTS v2.11 is now installed. ***
```

**Comment by avullo** [comment]
Hi @eburgueno, thanks for reporting this.
I have now amended the situation by allowing the installation to complete in an environment wo sudo.
Note in the following I'm running the install script from a clone of master from the git repo, as this is where the update is present. I'm about to make a new release soon so that you can do the same as you did using 2.11.

root@24aa42811951:/opt# git clone https://github.com/Ensembl/Bio-DB-HTS
Cloning into 'Bio-DB-HTS'...
remote: Enumerating objects: 48, done.
remote: Counting objects: 100% (48/48), done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 3696 (delta 18), reused 34 (delta 12), pack-reused 3648
Receiving objects: 100% (3696/3696), 9.98 MiB | 963.00 KiB/s, done.
Resolving deltas: 100% (1991/1991), done.
root@24aa42811951:/opt# cd Bio-DB-HTS/
root@24aa42811951:/opt/Bio-DB-HTS# ./INSTALL.pl 
/opt/Bio-DB-HTS

*** Performing build in /tmp/amNQw_acZn ***
(...)
*** Installing Bio::DB::HTS system wide without sudo. ***

*** Make sure you have the right privileges. ***

*** Bio::DB::HTS v2.11 is now installed. ***
root@24aa42811951:/opt/Bio-DB-HTS# ll /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS.pm 
-r--r--r-- 1 root root 80180 Mar  8 10:42 /usr/local/lib/x86_64-linux-gnu/perl/5.26.1/Bio/DB/HTS.pm
root@24aa42811951:/opt/Bio-DB-HTS# PERL5LIB=/usr/local/lib/x86_64-linux-gnu/perl/5.26.1/
root@24aa42811951:/opt/Bio-DB-HTS# perl -MBio::DB::HTS -e ''
root@24aa42811951:/opt/Bio-DB-HTS# perl -MBio::DB::HTS -e 'use Bio::DB::HTS'
